[package]
name = "porto-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Complete typed client for the Yandex Porto RPC API"
license.workspace = true
publish = false

[dependencies]
prost.workspace = true

[build-dependencies]
prost-build.workspace = true
