set shell := ["bash", "-eu", "-o", "pipefail", "-c"]

runtime := env_var_or_default("CONTAINER_RUNTIME", "docker")
image := env_var_or_default("IMAGE", "axe-web")
version := `date +%Y-%m-%dT%H.%M`

default: push

build tag=version:
    {{ runtime }} build --pull --tag {{ image }}:{{ tag }} .

push tag=version: (build tag)
    {{ runtime }} push {{ image }}:{{ tag }}
    @printf '\nWell done!\nUploaded: %s:%s\n' '{{ image }}' '{{ tag }}'
